graph LR
  linkStyle default fill:#ffffff

  subgraph diagram ["Claim Document Storage - Web Application - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 4 ["Web Application"]
      style 4 fill:#ffffff,stroke:#2e6295,color:#2e6295

      5("<div style='font-weight: bold'>Claim Documents Controller</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>")
      style 5 fill:#85bbf0,stroke:#5d82a8,color:#000000
      6("<div style='font-weight: bold'>Claim Document UseCases</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>")
      style 6 fill:#85bbf0,stroke:#5d82a8,color:#000000
      7("<div style='font-weight: bold'>Claim Document Services</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>")
      style 7 fill:#85bbf0,stroke:#5d82a8,color:#000000
      8("<div style='font-weight: bold'>Claim Document Repository</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div>")
      style 8 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

  end