graph LR
  linkStyle default fill:#ffffff

  subgraph diagram ["Claim Document Storage - Containers"]
    style diagram fill:#ffffff,stroke:#ffffff

    1["<div style='font-weight: bold'>User</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Policy Holder and/or<br />Claimant. Submits and Views<br />Claim Documents.</div>"]
    style 1 fill:#08427b,stroke:#052e56,color:#ffffff
    2["<div style='font-weight: bold'>Claim Admin</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Manages Claim Documents.</div>"]
    style 2 fill:#08427b,stroke:#052e56,color:#ffffff

    subgraph 3 ["Claim Document Storage"]
      style 3 fill:#ffffff,stroke:#0b4884,color:#0b4884

      11("<div style='font-weight: bold'>PostgreSQL DB</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div>")
      style 11 fill:#438dd5,stroke:#2e6295,color:#ffffff
      4("<div style='font-weight: bold'>Web Application</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div>")
      style 4 fill:#438dd5,stroke:#2e6295,color:#ffffff
      9("<div style='font-weight: bold'>Blob Storage (MinIO)</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div>")
      style 9 fill:#438dd5,stroke:#2e6295,color:#ffffff
    end

    1-. "<div>Submit and Update Documents</div><div style='font-size: 70%'></div>" .->4
    2-. "<div>Manage Claim Documents</div><div style='font-size: 70%'></div>" .->4
    1-. "<div>List Claims</div><div style='font-size: 70%'>[#?]</div>" .->4
    1-. "<div>Submit Claim Documents</div><div style='font-size: 70%'></div>" .->4
    1-. "<div>View Claim Document</div><div style='font-size: 70%'></div>" .->4
    1-. "<div>List Claim Documents</div><div style='font-size: 70%'></div>" .->4
    1-. "<div>Delete Claim Document</div><div style='font-size: 70%'></div>" .->4
    2-. "<div>List User Claims</div><div style='font-size: 70%'>[#??]</div>" .->4
    2-. "<div>Submit User Claim Documents</div><div style='font-size: 70%'></div>" .->4
    2-. "<div>View User Claim Document</div><div style='font-size: 70%'></div>" .->4
    2-. "<div>List User Claim Documents</div><div style='font-size: 70%'></div>" .->4
    2-. "<div>Delete User Claim Document</div><div style='font-size: 70%'></div>" .->4
    4-. "<div>Store Claim Document DB</div><div style='font-size: 70%'></div>" .->11
    4-. "<div>Store Claim Blob Objects</div><div style='font-size: 70%'></div>" .->9
  end